To setup Grails to use an HTTP proxy there are two steps. Firstly you need to configure the `grails` CLI to be aware of the proxy if you wish to use it to create applications and so on. This can be done using the `GRAILS_OPTS` environment variable, for example on Unix systems:

[source,bash]
----
export GRAILS_OPTS="-Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=3128 -Dhttp.proxyUser=test -Dhttp.proxyPassword=test"
----

NOTE: The default profile repository is resolved over HTTPS so `https.proxyPort` and `https.proxyUser` are used, however the username and password are specified with `http.proxyUser` and `http.proxyPassword`

For Windows systems the environment variable can be configured under `My Computer/Advanced/Environment Variables`.

With this configuration in place the `grails` command can connect and authenticate via a proxy.

Secondly, since Grails uses Gradle as the build system, you need to configure Gradle to authenticate via the proxy. For instructions on how to do this see the https://docs.gradle.org/current/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy[Gradle user guide section on the topic].

For Grails 3.3.5 
Although Grails is based on Gradle build system, Spring Framework used behind the scenes seems to use Eclipse Aether project
(https://projects.eclipse.org/projects/technology.aether) that in turn has dependency on Maven. 
In case you are receiving "Bad Gateway (502)" or "Connection Refused" errors right after running Grails CLI for first time,
add configuration for maven proxy in to $HOME/.m2/settings.xml (%USERPROFILE%\.m2\settings.xml)
...
<proxies>
    <proxy>
      <id>my-proxy</id>
      <active>true</active>
      <protocol>http</protocol>
      <host>localhost</host>
      <port>8888</port>
      <!-- nonProxyHosts>localhost|*.int</nonProxyHosts -->
    </proxy>
</proxies>
...

This should bring in Grails Profiles.
More info on syntax https://maven.apache.org/guides/mini/guide-proxies.html
